# -*- coding:utf-8 -*-

paises = [('BR',u'Brasil'),
          ('AF',u'Afeganistão'),
          ('ZA',u'África do Sul'),
          ('AX',u'Åland, Ilhas'),
          ('AL',u'Albânia'),
          ('DE',u'Alemanha'),
          ('AD',u'Andorra'),
          ('AO',u'Angola'),
          ('AI',u'Anguilla'),
          ('AQ',u'Antárctida'),
          ('AG',u'Antígua e Barbuda'),
          ('AN',u'Antilhas Holandesas'),
          ('SA',u'Arábia Saudita'),
          ('DZ',u'Argélia'),
          ('AR',u'Argentina'),
          ('AM',u'Armênia'),
          ('AW',u'Aruba'),
          ('AU',u'Austrália'),
          ('AT',u'Áustria'),
          ('AZ',u'Azerbaijão'),
          ('BS',u'Bahamas'),
          ('BH',u'Bahrain'),
          ('BD',u'Bangladesh'),
          ('BB',u'Barbados'),
          ('BE',u'Bélgica'),
          ('BZ',u'Belize'),
          ('BJ',u'Benim'),
          ('BM',u'Bermudas'),
          ('BY',u'Bielorrússia'),
          ('BO',u'Bolívia'),
          ('BA',u'Bósnia e Herzegovina'),
          ('BW',u'Botswana'),
          ('BV',u'Bouvet, Ilha'),
          ('BN',u'Brunei'),
          ('BG',u'Bulgária'),
          ('BF',u'Burkina Faso'),
          ('BI',u'Burundi'),
          ('BT',u'Butão'),
          ('CV',u'Cabo Verde'),
          ('KH',u'Cambodja'),
          ('CM',u'Camarões'),
          ('CA',u'Canadá'),
          ('KY',u'Cayman, Ilhas'),
          ('KZ',u'Cazaquistão'),
          ('CF',u'Centro-Africana, República'),
          ('TD',u'Chade'),
          ('CZ',u'Checa, República'),
          ('CL',u'Chile'),
          ('CN',u'China'),
          ('CY',u'Chipre'),
          ('CX',u'Christmas, Ilha'),
          ('CC',u'Cocos, Ilhas'),
          ('CO',u'Colômbia'),
          ('KM',u'Comores'),
          ('CG',u'Congo, República do'),
          ('CD',u'Congo, República Democrática do (antigo Zaire)'),
          ('CK',u'Cook, Ilhas'),
          ('KR',u'Coréia do Sul'),
          ('KP',u'Coreia, República Democrática da (Coreia do Norte)'),
          ('CI',u'Costa do Marfim'),
          ('CR',u'Costa Rica'),
          ('HR',u'Croácia'),
          ('CU',u'Cuba'),
          ('DK',u'Dinamarca'),
          ('DJ',u'Djibouti'),
          ('DM',u'Dominica'),
          ('DO',u'Dominicana, República'),
          ('EG',u'Egito'),
          ('SV',u'El Salvador'),
          ('AE',u'Emirados Árabes Unidos'),
          ('EC',u'Equador'),
          ('ER',u'Eritreia'),
          ('SK',u'Eslováquia'),
          ('SI',u'Eslovênia'),
          ('ES',u'Espanha'),
          ('US',u'Estados Unidos da América'),
          ('EE',u'Estónia'),
          ('ET',u'Etiópia'),
          ('FO',u'Feroé, Ilhas'),
          ('FJ',u'Fiji'),
          ('PH',u'Filipinas'),
          ('FI',u'Finlândia'),
          ('FR',u'França'),
          ('GA',u'Gabão'),
          ('GM',u'Gâmbia'),
          ('GH',u'Gana'),
          ('GE',u'Geórgia'),
          ('GS',u'Geórgia do Sul e Sandwich do Sul, Ilhas'),
          ('GI',u'Gibraltar'),
          ('GR',u'Grécia'),
          ('GD',u'Grenada'),
          ('GL',u'Groenlândia'),
          ('GP',u'Guadalupe'),
          ('GU',u'Guam'),
          ('GT',u'Guatemala'),
          ('GG',u'Guernsey'),
          ('GY',u'Guiana'),
          ('GF',u'Guiana Francesa'),
          ('GW',u'Guiné-Bissau'),
          ('GN',u'Guiné-Conacri'),
          ('GQ',u'Guiné Equatorial'),
          ('HT',u'Haiti'),
          ('HM',u'Heard e Ilhas McDonald, Ilha'),
          ('HN',u'Honduras'),
          ('HK',u'Hong Kong'),
          ('HU',u'Hungria'),
          ('YE',u'Iémen'),
          ('IN',u'Índia'),
          ('ID',u'Indonésia'),
          ('IQ',u'Iraque'),
          ('IR',u'Irã'),
          ('IE',u'Irlanda'),
          ('IS',u'Islândia'),
          ('IL',u'Israel'),
          ('IT',u'Itália'),
          ('JM',u'Jamaica'),
          ('JP',u'Japão'),
          ('JE',u'Jersey'),
          ('JO',u'Jordânia'),
          ('KI',u'Kiribati'),
          ('KW',u'Kuwait'),
          ('LA',u'Laos'),
          ('LS',u'Lesoto'),
          ('LV',u'Letônia'),
          ('LB',u'Líbano'),
          ('LR',u'Libéria'),
          ('LY',u'Líbia'),
          ('LI',u'Liechtenstein'),
          ('LT',u'Lituânia'),
          ('LU',u'Luxemburgo'),
          ('MO',u'Macau'),
          ('MK',u'Macedônia, República da'),
          ('MG',u'Madagáscar'),
          ('MY',u'Malásia'),
          ('MW',u'Malawi'),
          ('MV',u'Maldivas'),
          ('ML',u'Mali'),
          ('MT',u'Malta'),
          ('FK',u'Malvinas, Ilhas (Falkland)'),
          ('IM',u'Man, Ilha de'),
          ('MP',u'Marianas Setentrionais'),
          ('MA',u'Marrocos'),
          ('MH',u'Marshall, Ilhas'),
          ('MQ',u'Martinica'),
          ('MU',u'Maurícia'),
          ('MR',u'Mauritânia'),
          ('YT',u'Mayotte'),
          ('UM',u'Menores Distantes dos Estados Unidos, Ilhas'),
          ('MX',u'México'),
          ('MM',u'Myanmar (antiga Birmânia)'),
          ('FM',u'Micronésia, Estados Federados da'),
          ('MZ',u'Moçambique'),
          ('MD',u'Moldávia'),
          ('MC',u'Mônaco'),
          ('MN',u'Mongólia'),
          ('ME',u'Montenegro'),
          ('MS',u'Montserrat'),
          ('NA',u'Namíbia'),
          ('NR',u'Nauru'),
          ('NP',u'Nepal'),
          ('NI',u'Nicarágua'),
          ('NE',u'Níger'),
          ('NG',u'Nigéria'),
          ('NU',u'Niue'),
          ('NF',u'Norfolk, Ilha'),
          ('NO',u'Noruega'),
          ('NC',u'Nova Caledônia'),
          ('NZ',u'Nova Zelândia (Aotearoa)'),
          ('OM',u'Oman'),
          ('NL',u'Países Baixos (Holanda)'),
          ('PW',u'Palau'),
          ('PS',u'Palestina'),
          ('PA',u'Panamá'),
          ('PG',u'Papua-Nova Guiné'),
          ('PK',u'Paquistão'),
          ('PY',u'Paraguai'),
          ('PE',u'Peru'),
          ('PN',u'Pitcairn'),
          ('PF',u'Polinésia Francesa'),
          ('PL',u'Polônia'),
          ('PR',u'Porto Rico'),
          ('PT',u'Portugal'),
          ('QA',u'Qatar'),
          ('KE',u'Quênia'),
          ('KG',u'Quirguistão'),
          ('GB',u'Reino Unido da Grã-Bretanha e Irlanda do Norte'),
          ('RE',u'Reunião'),
          ('RO',u'Romênia'),
          ('RW',u'Ruanda'),
          ('RU',u'Rússia'),
          ('EH',u'Saara Ocidental'),
          ('AS',u'Samoa Americana'),
          ('WS',u'Samoa (Samoa Ocidental)'),
          ('PM',u'Saint Pierre et Miquelon'),
          ('SB',u'Salomão, Ilhas'),
          ('KN',u'São Cristóvão e Névis (Saint Kitts e Nevis)'),
          ('SM',u'San Marino'),
          ('ST',u'São Tomé e Príncipe'),
          ('VC',u'São Vicente e Granadinas'),
          ('SH',u'Santa Helena'),
          ('LC',u'Santa Lúcia'),
          ('SN',u'Senegal'),
          ('SL',u'Serra Leoa'),
          ('RS',u'Sérvia'),
          ('SC',u'Seychelles'),
          ('SG',u'Singapura'),
          ('SY',u'Síria'),
          ('SO',u'Somália'),
          ('LK',u'Sri Lanka'),
          ('SZ',u'Suazilândia'),
          ('SD',u'Sudão'),
          ('SE',u'Suécia'),
          ('CH',u'Suíça'),
          ('SR',u'Suriname'),
          ('SJ',u'Svalbard e Jan Mayen'),
          ('TH',u'Tailândia'),
          ('TW',u'Taiwan'),
          ('TJ',u'Tajiquistão'),
          ('TZ',u'Tanzânia'),
          ('TF',u'Terras Austrais e Antárticas Francesas (TAAF)'),
          ('IO',u'Território Britânico do Oceano Índico'),
          ('TL',u'Timor-Leste'),
          ('TG',u'Togo'),
          ('TK',u'Toquelau'),
          ('TO',u'Tonga'),
          ('TT',u'Trindade e Tobago'),
          ('TN',u'Tunísia'),
          ('TC',u'Turks e Caicos'),
          ('TM',u'Turquemenistão'),
          ('TR',u'Turquia'),
          ('TV',u'Tuvalu'),
          ('UA',u'Ucrânia'),
          ('UG',u'Uganda'),
          ('UY',u'Uruguai'),
          ('UZ',u'Usbequistão'),
          ('VU',u'Vanuatu'),
          ('VA',u'Vaticano'),
          ('VE',u'Venezuela'),
          ('VN',u'Vietnam'),
          ('VI',u'Virgens Americanas, Ilhas'),
          ('VG',u'Virgens Britânicas, Ilhas'),
          ('WF',u'Wallis e Futuna'),
          ('ZM',u'Zâmbia'),
          ('ZW',u'Zimbabwe'),]